"""rename address

Revision ID: 68fff79f9d58
Revises: 9b45c9c750af
Create Date: 2024-06-25 14:42:59.774739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fff79f9d58'
down_revision = '9b45c9c750af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name = 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name = 'address')
    # ### end Alembic commands ###
