"""rename department

Revision ID: 9b45c9c750af
Revises: 20413286f733
Create Date: 2024-06-25 14:31:41.147539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b45c9c750af'
down_revision = '20413286f733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments','department')
